//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace MyScience.MyScienceService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/MyScienceServiceWebRole")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string FormField;
        
        private int IDField;
        
        private string NameField;
        
        private int OwnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Form {
            get {
                return this.FormField;
            }
            set {
                if ((object.ReferenceEquals(this.FormField, value) != true)) {
                    this.FormField = value;
                    this.RaisePropertyChanged("Form");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((this.OwnerField.Equals(value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Submission", Namespace="http://schemas.datacontract.org/2004/07/MyScienceServiceWebRole")]
    public partial class Submission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DataField;
        
        private int IDField;
        
        private byte[] ImageDataField;
        
        private string ImageNameField;
        
        private string LocationField;
        
        private int ProjectIDField;
        
        private string ProjectNameField;
        
        private System.DateTime TimeField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopScorer", Namespace="http://schemas.datacontract.org/2004/07/MyScienceServiceWebRole")]
    public partial class TopScorer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        private int ScoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/MyScienceServiceWebRole")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        private string PhoneIDField;
        
        private int ScoreField;
        
        private int hasImageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneID {
            get {
                return this.PhoneIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneIDField, value) != true)) {
                    this.PhoneIDField = value;
                    this.RaisePropertyChanged("PhoneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hasImage {
            get {
                return this.hasImageField;
            }
            set {
                if ((this.hasImageField.Equals(value) != true)) {
                    this.hasImageField = value;
                    this.RaisePropertyChanged("hasImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyScienceService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetProjects", ReplyAction="http://tempuri.org/IService1/GetProjectsResponse")]
        System.IAsyncResult BeginGetProjects(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> EndGetProjects(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SubmitData", ReplyAction="http://tempuri.org/IService1/SubmitDataResponse")]
        System.IAsyncResult BeginSubmitData(MyScience.MyScienceService.Submission newsubmission, System.AsyncCallback callback, object asyncState);
        
        System.Uri EndSubmitData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTopScorers", ReplyAction="http://tempuri.org/IService1/GetTopScorersResponse")]
        System.IAsyncResult BeginGetTopScorers(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> EndGetTopScorers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserProfile", ReplyAction="http://tempuri.org/IService1/GetUserProfileResponse")]
        System.IAsyncResult BeginGetUserProfile(string username, string phoneID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> EndGetUserProfile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.IAsyncResult BeginRegisterUser(int id, string phoneid, string name, System.AsyncCallback callback, object asyncState);
        
        MyScience.MyScienceService.User EndRegisterUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/RegisterUserWithImage", ReplyAction="http://tempuri.org/IService1/RegisterUserWithImageResponse")]
        System.IAsyncResult BeginRegisterUserWithImage(int id, string phoneid, string name, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState);
        
        MyScience.MyScienceService.User EndRegisterUserWithImage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetProjectDataNum", ReplyAction="http://tempuri.org/IService1/GetProjectDataNumResponse")]
        System.IAsyncResult BeginGetProjectDataNum(int projectid, System.AsyncCallback callback, object asyncState);
        
        int EndGetProjectDataNum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserSubmission", ReplyAction="http://tempuri.org/IService1/GetUserSubmissionResponse")]
        System.IAsyncResult BeginGetUserSubmission(int userid, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> EndGetUserSubmission(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetUserImage", ReplyAction="http://tempuri.org/IService1/GetUserImageResponse")]
        System.IAsyncResult BeginGetUserImage(string username, string contentType, System.AsyncCallback callback, object asyncState);
        
        byte[] EndGetUserImage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UploadUserImage", ReplyAction="http://tempuri.org/IService1/UploadUserImageResponse")]
        System.IAsyncResult BeginUploadUserImage(string username, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState);
        
        int EndUploadUserImage(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyScience.MyScienceService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Uri Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Uri)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTopScorersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTopScorersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyScience.MyScienceService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyScience.MyScienceService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterUserWithImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterUserWithImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MyScience.MyScienceService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MyScience.MyScienceService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProjectDataNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProjectDataNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserSubmissionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserSubmissionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadUserImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UploadUserImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyScience.MyScienceService.IService1>, MyScience.MyScienceService.IService1 {
        
        private BeginOperationDelegate onBeginGetProjectsDelegate;
        
        private EndOperationDelegate onEndGetProjectsDelegate;
        
        private System.Threading.SendOrPostCallback onGetProjectsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitDataDelegate;
        
        private EndOperationDelegate onEndSubmitDataDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTopScorersDelegate;
        
        private EndOperationDelegate onEndGetTopScorersDelegate;
        
        private System.Threading.SendOrPostCallback onGetTopScorersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserProfileDelegate;
        
        private EndOperationDelegate onEndGetUserProfileDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserProfileCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterUserDelegate;
        
        private EndOperationDelegate onEndRegisterUserDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginRegisterUserWithImageDelegate;
        
        private EndOperationDelegate onEndRegisterUserWithImageDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterUserWithImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProjectDataNumDelegate;
        
        private EndOperationDelegate onEndGetProjectDataNumDelegate;
        
        private System.Threading.SendOrPostCallback onGetProjectDataNumCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserSubmissionDelegate;
        
        private EndOperationDelegate onEndGetUserSubmissionDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserSubmissionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserImageDelegate;
        
        private EndOperationDelegate onEndGetUserImageDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadUserImageDelegate;
        
        private EndOperationDelegate onEndUploadUserImageDelegate;
        
        private System.Threading.SendOrPostCallback onUploadUserImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetProjectsCompletedEventArgs> GetProjectsCompleted;
        
        public event System.EventHandler<SubmitDataCompletedEventArgs> SubmitDataCompleted;
        
        public event System.EventHandler<GetTopScorersCompletedEventArgs> GetTopScorersCompleted;
        
        public event System.EventHandler<GetUserProfileCompletedEventArgs> GetUserProfileCompleted;
        
        public event System.EventHandler<RegisterUserCompletedEventArgs> RegisterUserCompleted;
        
        public event System.EventHandler<RegisterUserWithImageCompletedEventArgs> RegisterUserWithImageCompleted;
        
        public event System.EventHandler<GetProjectDataNumCompletedEventArgs> GetProjectDataNumCompleted;
        
        public event System.EventHandler<GetUserSubmissionCompletedEventArgs> GetUserSubmissionCompleted;
        
        public event System.EventHandler<GetUserImageCompletedEventArgs> GetUserImageCompleted;
        
        public event System.EventHandler<UploadUserImageCompletedEventArgs> UploadUserImageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetProjects(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProjects(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> MyScience.MyScienceService.IService1.EndGetProjects(System.IAsyncResult result) {
            return base.Channel.EndGetProjects(result);
        }
        
        private System.IAsyncResult OnBeginGetProjects(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetProjects(callback, asyncState);
        }
        
        private object[] OnEndGetProjects(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetProjects(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProjectsCompleted(object state) {
            if ((this.GetProjectsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProjectsCompleted(this, new GetProjectsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProjectsAsync() {
            this.GetProjectsAsync(null);
        }
        
        public void GetProjectsAsync(object userState) {
            if ((this.onBeginGetProjectsDelegate == null)) {
                this.onBeginGetProjectsDelegate = new BeginOperationDelegate(this.OnBeginGetProjects);
            }
            if ((this.onEndGetProjectsDelegate == null)) {
                this.onEndGetProjectsDelegate = new EndOperationDelegate(this.OnEndGetProjects);
            }
            if ((this.onGetProjectsCompletedDelegate == null)) {
                this.onGetProjectsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProjectsCompleted);
            }
            base.InvokeAsync(this.onBeginGetProjectsDelegate, null, this.onEndGetProjectsDelegate, this.onGetProjectsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginSubmitData(MyScience.MyScienceService.Submission newsubmission, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitData(newsubmission, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Uri MyScience.MyScienceService.IService1.EndSubmitData(System.IAsyncResult result) {
            return base.Channel.EndSubmitData(result);
        }
        
        private System.IAsyncResult OnBeginSubmitData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MyScience.MyScienceService.Submission newsubmission = ((MyScience.MyScienceService.Submission)(inValues[0]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginSubmitData(newsubmission, callback, asyncState);
        }
        
        private object[] OnEndSubmitData(System.IAsyncResult result) {
            System.Uri retVal = ((MyScience.MyScienceService.IService1)(this)).EndSubmitData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitDataCompleted(object state) {
            if ((this.SubmitDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitDataCompleted(this, new SubmitDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitDataAsync(MyScience.MyScienceService.Submission newsubmission) {
            this.SubmitDataAsync(newsubmission, null);
        }
        
        public void SubmitDataAsync(MyScience.MyScienceService.Submission newsubmission, object userState) {
            if ((this.onBeginSubmitDataDelegate == null)) {
                this.onBeginSubmitDataDelegate = new BeginOperationDelegate(this.OnBeginSubmitData);
            }
            if ((this.onEndSubmitDataDelegate == null)) {
                this.onEndSubmitDataDelegate = new EndOperationDelegate(this.OnEndSubmitData);
            }
            if ((this.onSubmitDataCompletedDelegate == null)) {
                this.onSubmitDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitDataCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitDataDelegate, new object[] {
                        newsubmission}, this.onEndSubmitDataDelegate, this.onSubmitDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetTopScorers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTopScorers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> MyScience.MyScienceService.IService1.EndGetTopScorers(System.IAsyncResult result) {
            return base.Channel.EndGetTopScorers(result);
        }
        
        private System.IAsyncResult OnBeginGetTopScorers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetTopScorers(callback, asyncState);
        }
        
        private object[] OnEndGetTopScorers(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetTopScorers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTopScorersCompleted(object state) {
            if ((this.GetTopScorersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTopScorersCompleted(this, new GetTopScorersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTopScorersAsync() {
            this.GetTopScorersAsync(null);
        }
        
        public void GetTopScorersAsync(object userState) {
            if ((this.onBeginGetTopScorersDelegate == null)) {
                this.onBeginGetTopScorersDelegate = new BeginOperationDelegate(this.OnBeginGetTopScorers);
            }
            if ((this.onEndGetTopScorersDelegate == null)) {
                this.onEndGetTopScorersDelegate = new EndOperationDelegate(this.OnEndGetTopScorers);
            }
            if ((this.onGetTopScorersCompletedDelegate == null)) {
                this.onGetTopScorersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTopScorersCompleted);
            }
            base.InvokeAsync(this.onBeginGetTopScorersDelegate, null, this.onEndGetTopScorersDelegate, this.onGetTopScorersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetUserProfile(string username, string phoneID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserProfile(username, phoneID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> MyScience.MyScienceService.IService1.EndGetUserProfile(System.IAsyncResult result) {
            return base.Channel.EndGetUserProfile(result);
        }
        
        private System.IAsyncResult OnBeginGetUserProfile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string phoneID = ((string)(inValues[1]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetUserProfile(username, phoneID, callback, asyncState);
        }
        
        private object[] OnEndGetUserProfile(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetUserProfile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserProfileCompleted(object state) {
            if ((this.GetUserProfileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserProfileCompleted(this, new GetUserProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserProfileAsync(string username, string phoneID) {
            this.GetUserProfileAsync(username, phoneID, null);
        }
        
        public void GetUserProfileAsync(string username, string phoneID, object userState) {
            if ((this.onBeginGetUserProfileDelegate == null)) {
                this.onBeginGetUserProfileDelegate = new BeginOperationDelegate(this.OnBeginGetUserProfile);
            }
            if ((this.onEndGetUserProfileDelegate == null)) {
                this.onEndGetUserProfileDelegate = new EndOperationDelegate(this.OnEndGetUserProfile);
            }
            if ((this.onGetUserProfileCompletedDelegate == null)) {
                this.onGetUserProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserProfileCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserProfileDelegate, new object[] {
                        username,
                        phoneID}, this.onEndGetUserProfileDelegate, this.onGetUserProfileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginRegisterUser(int id, string phoneid, string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterUser(id, phoneid, name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyScience.MyScienceService.User MyScience.MyScienceService.IService1.EndRegisterUser(System.IAsyncResult result) {
            return base.Channel.EndRegisterUser(result);
        }
        
        private System.IAsyncResult OnBeginRegisterUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            string phoneid = ((string)(inValues[1]));
            string name = ((string)(inValues[2]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginRegisterUser(id, phoneid, name, callback, asyncState);
        }
        
        private object[] OnEndRegisterUser(System.IAsyncResult result) {
            MyScience.MyScienceService.User retVal = ((MyScience.MyScienceService.IService1)(this)).EndRegisterUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterUserCompleted(object state) {
            if ((this.RegisterUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterUserCompleted(this, new RegisterUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterUserAsync(int id, string phoneid, string name) {
            this.RegisterUserAsync(id, phoneid, name, null);
        }
        
        public void RegisterUserAsync(int id, string phoneid, string name, object userState) {
            if ((this.onBeginRegisterUserDelegate == null)) {
                this.onBeginRegisterUserDelegate = new BeginOperationDelegate(this.OnBeginRegisterUser);
            }
            if ((this.onEndRegisterUserDelegate == null)) {
                this.onEndRegisterUserDelegate = new EndOperationDelegate(this.OnEndRegisterUser);
            }
            if ((this.onRegisterUserCompletedDelegate == null)) {
                this.onRegisterUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterUserCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterUserDelegate, new object[] {
                        id,
                        phoneid,
                        name}, this.onEndRegisterUserDelegate, this.onRegisterUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginRegisterUserWithImage(int id, string phoneid, string name, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterUserWithImage(id, phoneid, name, contentType, imagedata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyScience.MyScienceService.User MyScience.MyScienceService.IService1.EndRegisterUserWithImage(System.IAsyncResult result) {
            return base.Channel.EndRegisterUserWithImage(result);
        }
        
        private System.IAsyncResult OnBeginRegisterUserWithImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            string phoneid = ((string)(inValues[1]));
            string name = ((string)(inValues[2]));
            string contentType = ((string)(inValues[3]));
            byte[] imagedata = ((byte[])(inValues[4]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginRegisterUserWithImage(id, phoneid, name, contentType, imagedata, callback, asyncState);
        }
        
        private object[] OnEndRegisterUserWithImage(System.IAsyncResult result) {
            MyScience.MyScienceService.User retVal = ((MyScience.MyScienceService.IService1)(this)).EndRegisterUserWithImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterUserWithImageCompleted(object state) {
            if ((this.RegisterUserWithImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterUserWithImageCompleted(this, new RegisterUserWithImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterUserWithImageAsync(int id, string phoneid, string name, string contentType, byte[] imagedata) {
            this.RegisterUserWithImageAsync(id, phoneid, name, contentType, imagedata, null);
        }
        
        public void RegisterUserWithImageAsync(int id, string phoneid, string name, string contentType, byte[] imagedata, object userState) {
            if ((this.onBeginRegisterUserWithImageDelegate == null)) {
                this.onBeginRegisterUserWithImageDelegate = new BeginOperationDelegate(this.OnBeginRegisterUserWithImage);
            }
            if ((this.onEndRegisterUserWithImageDelegate == null)) {
                this.onEndRegisterUserWithImageDelegate = new EndOperationDelegate(this.OnEndRegisterUserWithImage);
            }
            if ((this.onRegisterUserWithImageCompletedDelegate == null)) {
                this.onRegisterUserWithImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterUserWithImageCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterUserWithImageDelegate, new object[] {
                        id,
                        phoneid,
                        name,
                        contentType,
                        imagedata}, this.onEndRegisterUserWithImageDelegate, this.onRegisterUserWithImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetProjectDataNum(int projectid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProjectDataNum(projectid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int MyScience.MyScienceService.IService1.EndGetProjectDataNum(System.IAsyncResult result) {
            return base.Channel.EndGetProjectDataNum(result);
        }
        
        private System.IAsyncResult OnBeginGetProjectDataNum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int projectid = ((int)(inValues[0]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetProjectDataNum(projectid, callback, asyncState);
        }
        
        private object[] OnEndGetProjectDataNum(System.IAsyncResult result) {
            int retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetProjectDataNum(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProjectDataNumCompleted(object state) {
            if ((this.GetProjectDataNumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProjectDataNumCompleted(this, new GetProjectDataNumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProjectDataNumAsync(int projectid) {
            this.GetProjectDataNumAsync(projectid, null);
        }
        
        public void GetProjectDataNumAsync(int projectid, object userState) {
            if ((this.onBeginGetProjectDataNumDelegate == null)) {
                this.onBeginGetProjectDataNumDelegate = new BeginOperationDelegate(this.OnBeginGetProjectDataNum);
            }
            if ((this.onEndGetProjectDataNumDelegate == null)) {
                this.onEndGetProjectDataNumDelegate = new EndOperationDelegate(this.OnEndGetProjectDataNum);
            }
            if ((this.onGetProjectDataNumCompletedDelegate == null)) {
                this.onGetProjectDataNumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProjectDataNumCompleted);
            }
            base.InvokeAsync(this.onBeginGetProjectDataNumDelegate, new object[] {
                        projectid}, this.onEndGetProjectDataNumDelegate, this.onGetProjectDataNumCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetUserSubmission(int userid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserSubmission(userid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> MyScience.MyScienceService.IService1.EndGetUserSubmission(System.IAsyncResult result) {
            return base.Channel.EndGetUserSubmission(result);
        }
        
        private System.IAsyncResult OnBeginGetUserSubmission(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int userid = ((int)(inValues[0]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetUserSubmission(userid, callback, asyncState);
        }
        
        private object[] OnEndGetUserSubmission(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetUserSubmission(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserSubmissionCompleted(object state) {
            if ((this.GetUserSubmissionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserSubmissionCompleted(this, new GetUserSubmissionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserSubmissionAsync(int userid) {
            this.GetUserSubmissionAsync(userid, null);
        }
        
        public void GetUserSubmissionAsync(int userid, object userState) {
            if ((this.onBeginGetUserSubmissionDelegate == null)) {
                this.onBeginGetUserSubmissionDelegate = new BeginOperationDelegate(this.OnBeginGetUserSubmission);
            }
            if ((this.onEndGetUserSubmissionDelegate == null)) {
                this.onEndGetUserSubmissionDelegate = new EndOperationDelegate(this.OnEndGetUserSubmission);
            }
            if ((this.onGetUserSubmissionCompletedDelegate == null)) {
                this.onGetUserSubmissionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserSubmissionCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserSubmissionDelegate, new object[] {
                        userid}, this.onEndGetUserSubmissionDelegate, this.onGetUserSubmissionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginGetUserImage(string username, string contentType, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserImage(username, contentType, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] MyScience.MyScienceService.IService1.EndGetUserImage(System.IAsyncResult result) {
            return base.Channel.EndGetUserImage(result);
        }
        
        private System.IAsyncResult OnBeginGetUserImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string contentType = ((string)(inValues[1]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginGetUserImage(username, contentType, callback, asyncState);
        }
        
        private object[] OnEndGetUserImage(System.IAsyncResult result) {
            byte[] retVal = ((MyScience.MyScienceService.IService1)(this)).EndGetUserImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserImageCompleted(object state) {
            if ((this.GetUserImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserImageCompleted(this, new GetUserImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserImageAsync(string username, string contentType) {
            this.GetUserImageAsync(username, contentType, null);
        }
        
        public void GetUserImageAsync(string username, string contentType, object userState) {
            if ((this.onBeginGetUserImageDelegate == null)) {
                this.onBeginGetUserImageDelegate = new BeginOperationDelegate(this.OnBeginGetUserImage);
            }
            if ((this.onEndGetUserImageDelegate == null)) {
                this.onEndGetUserImageDelegate = new EndOperationDelegate(this.OnEndGetUserImage);
            }
            if ((this.onGetUserImageCompletedDelegate == null)) {
                this.onGetUserImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserImageCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserImageDelegate, new object[] {
                        username,
                        contentType}, this.onEndGetUserImageDelegate, this.onGetUserImageCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MyScience.MyScienceService.IService1.BeginUploadUserImage(string username, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadUserImage(username, contentType, imagedata, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int MyScience.MyScienceService.IService1.EndUploadUserImage(System.IAsyncResult result) {
            return base.Channel.EndUploadUserImage(result);
        }
        
        private System.IAsyncResult OnBeginUploadUserImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string contentType = ((string)(inValues[1]));
            byte[] imagedata = ((byte[])(inValues[2]));
            return ((MyScience.MyScienceService.IService1)(this)).BeginUploadUserImage(username, contentType, imagedata, callback, asyncState);
        }
        
        private object[] OnEndUploadUserImage(System.IAsyncResult result) {
            int retVal = ((MyScience.MyScienceService.IService1)(this)).EndUploadUserImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUploadUserImageCompleted(object state) {
            if ((this.UploadUserImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadUserImageCompleted(this, new UploadUserImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadUserImageAsync(string username, string contentType, byte[] imagedata) {
            this.UploadUserImageAsync(username, contentType, imagedata, null);
        }
        
        public void UploadUserImageAsync(string username, string contentType, byte[] imagedata, object userState) {
            if ((this.onBeginUploadUserImageDelegate == null)) {
                this.onBeginUploadUserImageDelegate = new BeginOperationDelegate(this.OnBeginUploadUserImage);
            }
            if ((this.onEndUploadUserImageDelegate == null)) {
                this.onEndUploadUserImageDelegate = new EndOperationDelegate(this.OnEndUploadUserImage);
            }
            if ((this.onUploadUserImageCompletedDelegate == null)) {
                this.onUploadUserImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadUserImageCompleted);
            }
            base.InvokeAsync(this.onBeginUploadUserImageDelegate, new object[] {
                        username,
                        contentType,
                        imagedata}, this.onEndUploadUserImageDelegate, this.onUploadUserImageCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MyScience.MyScienceService.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<MyScience.MyScienceService.IService1>, MyScience.MyScienceService.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<MyScience.MyScienceService.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetProjects(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetProjects", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> EndGetProjects(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project> _result = ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Project>)(base.EndInvoke("GetProjects", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSubmitData(MyScience.MyScienceService.Submission newsubmission, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = newsubmission;
                System.IAsyncResult _result = base.BeginInvoke("SubmitData", _args, callback, asyncState);
                return _result;
            }
            
            public System.Uri EndSubmitData(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Uri _result = ((System.Uri)(base.EndInvoke("SubmitData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTopScorers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTopScorers", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> EndGetTopScorers(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer> _result = ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.TopScorer>)(base.EndInvoke("GetTopScorers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserProfile(string username, string phoneID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = phoneID;
                System.IAsyncResult _result = base.BeginInvoke("GetUserProfile", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> EndGetUserProfile(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User> _result = ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.User>)(base.EndInvoke("GetUserProfile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegisterUser(int id, string phoneid, string name, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = id;
                _args[1] = phoneid;
                _args[2] = name;
                System.IAsyncResult _result = base.BeginInvoke("RegisterUser", _args, callback, asyncState);
                return _result;
            }
            
            public MyScience.MyScienceService.User EndRegisterUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyScience.MyScienceService.User _result = ((MyScience.MyScienceService.User)(base.EndInvoke("RegisterUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRegisterUserWithImage(int id, string phoneid, string name, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = id;
                _args[1] = phoneid;
                _args[2] = name;
                _args[3] = contentType;
                _args[4] = imagedata;
                System.IAsyncResult _result = base.BeginInvoke("RegisterUserWithImage", _args, callback, asyncState);
                return _result;
            }
            
            public MyScience.MyScienceService.User EndRegisterUserWithImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                MyScience.MyScienceService.User _result = ((MyScience.MyScienceService.User)(base.EndInvoke("RegisterUserWithImage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProjectDataNum(int projectid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = projectid;
                System.IAsyncResult _result = base.BeginInvoke("GetProjectDataNum", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetProjectDataNum(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetProjectDataNum", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserSubmission(int userid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = userid;
                System.IAsyncResult _result = base.BeginInvoke("GetUserSubmission", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> EndGetUserSubmission(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission> _result = ((System.Collections.ObjectModel.ObservableCollection<MyScience.MyScienceService.Submission>)(base.EndInvoke("GetUserSubmission", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserImage(string username, string contentType, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = contentType;
                System.IAsyncResult _result = base.BeginInvoke("GetUserImage", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndGetUserImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("GetUserImage", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUploadUserImage(string username, string contentType, byte[] imagedata, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = contentType;
                _args[2] = imagedata;
                System.IAsyncResult _result = base.BeginInvoke("UploadUserImage", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUploadUserImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UploadUserImage", _args, result)));
                return _result;
            }
        }
    }
}
